export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_CURRENCY_LIST_FULFILLED = 'GET_CURRENCY_LIST_FULFILLED';
export const GET_CURRENCY_LIST_REJECTED = 'GET_CURRENCY_LIST_REJECTED';
export const CURRENCY_LIST_FILTERED = 'CURRENCY_LIST_FILTERED';
export const SELECTED_CURRENCY = 'SELECTED_CURRENCY';
export const ADD_CURRENCY_TO_FAVOURITE = 'ADD_CURRENCY_TO_FAVOURITE';
