export const ADD_TODO = '[MY_PROJ][TODO] ADD_TODO';
export const REMOVE_TODO = '[MY_PROJ][TODO] REMOVE_TODO';
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_CURRENCY_LIST_FULFILLED = 'GET_CURRENCY_LIST_FULFILLED';
export const GET_CURRENCY_LIST_REJECTED = 'GET_CURRENCY_LIST_REJECTED';
export const CURRENCY_LIST_FILTERED = 'CURRENCY_LIST_FILTERED';
